"""add row is_admin and is_farmer to User table

Revision ID: 64024b33ad87
Revises: e10cef503a52
Create Date: 2019-10-30 11:10:12.541158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64024b33ad87'
down_revision = 'e10cef503a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_farmer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_farmer')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
