"""add aliment table

Revision ID: e10cef503a52
Revises: b771938842c0
Create Date: 2019-10-28 17:25:55.119956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10cef503a52'
down_revision = 'b771938842c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aliment_name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliments')
    # ### end Alembic commands ###
